# Generated by Django 5.2.7 on 2025-10-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('safe', 'Safe'), ('unsafe', 'Unsafe')], default='pending', max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
