# Generated by Django 5.2.7 on 2025-10-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator')], default='user', max_length=10)),
            ],
        ),
    ]
